[package]
name = "procfs"
version = "0.5.2"
authors = ["Andrew Chin <achin@eminence32.net>"]
repository = "https://github.com/eminence/procfs"
description = "Interface to the linux procfs pseudo-filesystem"
readme = "README.md"
keywords = ["procfs", "proc", "linux", "process"]
categories = ["os::unix-apis", "filesystem"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
libc = "0.2"
bitflags = "1"
lazy_static = "1"
chrono = "0.4"
byteorder = {version="1", features=["i128"]}
hex = "0.3"
libflate = "0.1"

[dev-dependencies]
failure = "0.1.5"
